# 基础镜像
FROM redis
# author
MAINTAINER auths

# 挂载目录
VOLUME /home/auths/redis
# 创建目录
RUN mkdir -p /home/auths/redis
# 指定路径
WORKDIR /home/auths/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/auths/redis/redis.conf
